#FROM debian:bullseye-slim
FROM ubuntu:20.04
FROM redis/redis-stack:7.2.0-v14

LABEL maintainer="Yingxi Yao <yingxi.yao@gmail.com>"
LABEL version="1.0"
LABEL description="docker for telecomAI database env"


# Install required tools and dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-11-jdk \
    systemd \
    curl \
    wget \
    ca-certificates \
    tar \
    gzip \
    gnupg \
    openssl \
    libssl-dev \
    supervisor \
    lsb-release gpg \
    mysql-server \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
    
# Install Redis
#RUN curl -O http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz \
#    && tar -xzf redis-${REDIS_VERSION}.tar.gz \
#    && cd redis-${REDIS_VERSION} && make && make install \
#    && cd .. && rm -rf redis-${REDIS_VERSION} redis-${REDIS_VERSION}.tar.gz

# Install MongoDB
RUN curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-8.0.4.tgz \
    && tar -xzf mongodb-linux-x86_64-ubuntu2004-8.0.4.tgz -C /opt \
    && mv /opt/mongodb-linux-x86_64-ubuntu2004-8.0.4 /opt/mongo \
    && rm mongodb-linux-x86_64-ubuntu2004-8.0.4.tgz \
# Download and install Zookeeper
    && curl -O  https://dlcdn.apache.org/zookeeper/zookeeper-3.8.4/apache-zookeeper-3.8.4-bin.tar.gz \
    && tar -xzf apache-zookeeper-3.8.4-bin.tar.gz -C /opt \
    && mv /opt/apache-zookeeper-3.8.4-bin /opt/zookeeper \
    && rm apache-zookeeper-3.8.4-bin.tar.gz \
# Download and install Kafka
    && curl -O  https://dlcdn.apache.org/kafka/3.8.1/kafka_2.13-3.8.1.tgz \
    && tar -xzf kafka_2.13-3.8.1.tgz -C /opt \
    && mv /opt/kafka_2.13-3.8.1 /opt/kafka \
    && rm kafka_2.13-3.8.1.tgz \
# Create directories for configurations and logs
    && mkdir -p /data/zookeeper1/ /data/zookeeper2/ /data/zookeeper3/ /data/kafka /data/mongo /data/mysql /data/redis /logs /opt/dciConfig \
    && echo 1 > /data/zookeeper1/myid \
    && echo 2 > /data/zookeeper2/myid \
    && echo 3 > /data/zookeeper3/myid 

# Copy custom entrypoint and config files
COPY config /opt/dciConfig
COPY entrypoint.sh /opt/dciConfig
RUN chmod +x /opt/dciConfig/entrypoint.sh  #FROM redis/redis-stack:7.2.0-v14 will automatically running its entrypoint and runing front

# Use the custom entrypoint
ENTRYPOINT ["/bin/bash"]
